return {
  { "kepano/flexoki-neovim", name = "flexoki" },
  { "ellisonleao/gruvbox.nvim" },
  { "catppuccin/nvim", name = "catppuccin" },
  { "sainnhe/everforest" },
  { "rebelot/kanagawa.nvim" },
  { "rose-pine/neovim", name = "rose-pine" },
  { "EdenEast/nightfox.nvim" },
  { "craftzdog/solarized-osaka.nvim" },
  { "nyoom-engineering/oxocarbon.nvim" },
  { "projekt0n/github-nvim-theme", name = "github-theme" },
  { "savq/melange-nvim" },
  { "miikanissi/modus-themes.nvim" },
  { "Mofiqul/dracula.nvim" },
  { "gbprod/nord.nvim" },
  { "sainnhe/sonokai" },
  { "maxmx03/solarized.nvim" },
  { "slugbyte/lackluster.nvim" },
  {
    "zenbones-theme/zenbones.nvim",
    dependencies = { "rktjmp/lush.nvim" },
  },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "flexoki-light",
    },
  },

  {
    "zaldih/themery.nvim",
    lazy = false,
    opts = {
      themes = {
        { name = "flexoki-light", colorscheme = "flexoki-light" },
        { name = "catppuccin-latte", colorscheme = "catppuccin-latte" },
        { name = "rose-pine-dawn", colorscheme = "rose-pine-dawn" },
        { name = "dayfox", colorscheme = "dayfox" },
        { name = "dawnfox", colorscheme = "dawnfox" },
        { name = "github-light", colorscheme = "github_light" },
        { name = "modus-operandi", colorscheme = "modus_operandi" },
        { name = "tokyonight-day", colorscheme = "tokyonight-day" },
        {
          name = "solarized-light",
          colorscheme = "solarized",
          before = [[vim.o.background = "light"]],
        },
        {
          name = "melange-light",
          colorscheme = "melange",
          before = [[vim.o.background = "light"]],
        },
        {
          name = "everforest-light",
          colorscheme = "everforest",
          before = [[vim.o.background = "light"]],
        },
        {
          name = "zenwritten-light",
          colorscheme = "zenwritten",
          before = [[vim.o.background = "light"]],
        },
        { name = "flexoki-dark", colorscheme = "flexoki-dark" },
        {
          name = "gruvbox",
          colorscheme = "gruvbox",
          before = [[vim.o.background = "dark"]],
        },
        { name = "catppuccin-mocha", colorscheme = "catppuccin-mocha" },
        {
          name = "everforest",
          colorscheme = "everforest",
          before = [[vim.o.background = "dark"]],
        },
        { name = "kanagawa", colorscheme = "kanagawa" },
        { name = "rose-pine", colorscheme = "rose-pine" },
        { name = "nightfox", colorscheme = "nightfox" },
        { name = "duskfox", colorscheme = "duskfox" },
        { name = "solarized-osaka", colorscheme = "solarized-osaka" },
        {
          name = "solarized-dark",
          colorscheme = "solarized",
          before = [[vim.o.background = "dark"]],
        },
        {
          name = "oxocarbon",
          colorscheme = "oxocarbon",
          before = [[vim.o.background = "dark"]],
        },
        { name = "github-dark", colorscheme = "github_dark" },
        { name = "modus-vivendi", colorscheme = "modus_vivendi" },
        {
          name = "melange",
          colorscheme = "melange",
          before = [[vim.o.background = "dark"]],
        },
        { name = "tokyonight-storm", colorscheme = "tokyonight-storm" },
        { name = "dracula", colorscheme = "dracula" },
        { name = "nord", colorscheme = "nord" },
        { name = "sonokai", colorscheme = "sonokai" },
        { name = "lackluster", colorscheme = "lackluster" },
        {
          name = "zenwritten-dark",
          colorscheme = "zenwritten",
          before = [[vim.o.background = "dark"]],
        },
      },
      livePreview = true,
    },
  },
}
